# Generated by Django 6.1 on 2026-09-22 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка (% в день)')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Макс. сумма (руб.)')),
                ('term_days', models.IntegerField(verbose_name='Срок (в днях)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма займа (руб.)')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paid', 'Погашен'), ('overdue', 'Просрочен')], default='active', max_length=10, verbose_name='Статус')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Займ',
                'verbose_name_plural': 'Займы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата и время платежа')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan', verbose_name='Заем')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
